travis:
  secure:
    BINSTAR_TOKEN: DD7GpjVssdYq2waf/WBMBhZiUTVD09aqphpldUl4HnAFgPIRE6zLyJDmLJU6zkXZmlmvQo87TLz2yPG7ORITC41pTZIyHwkSrF+5or+/BkyRoJaxKrdlEX5BhaNsSPNRoRTVo00biYKsbbQR+xOutuR7mULXCQwAxgGx3t9vGPQzgJXZ/V4bY3dXRdQh+4P/zGMeiL71DuZJAx+qRDm43BvbQeep3Z8+QDUBquceD9ZQx42ApJDAINQzDF/2AUcDcQfDuFE7+UBOIhEpYf8mDBnyDxMuOAqQhbYx39zdfMku1kl0oPrlTc0VbaSXDKADBOXHWAa1sO7l5cs62b7f2qAUCHDYUax2u1E35lQi7/L5ib3yOGO9QOFM0ooBH2j/tFg5amN3/sj95QsQtgylN8dJ565aOHwzYecj17Dk4r3UUqPbj8giEmFiBKFZCLSIIFf9FNHCbQ489mwakGU09GhY5gVokdiNrTrTvYH3KuiLUiDMynltWXKONiqKG9je42Hb+YNvHwNHk7s6Av29Hx0+RRhokwmsq3cvZU4ibMqvFsdbx2AjF0BxwwMj2/vT4+/UswfzGeQQ3afZsEfwWxayPoTKRuNHd6IEWBZsh4F+pHFtxU3ensDSlia25PeSGAHuFKiaqiPmUewao/WxBA0yuMBgV5KKAZrFH8ECOwQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
